// Code generated by ent, DO NOT EDIT.

package asset

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/adimail/asset-manager/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Asset {
	return predicate.Asset(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Asset {
	return predicate.Asset(sql.FieldContainsFold(FieldID, id))
}

// OriginalFilename applies equality check predicate on the "original_filename" field. It's identical to OriginalFilenameEQ.
func OriginalFilename(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldOriginalFilename, v))
}

// FileType applies equality check predicate on the "file_type" field. It's identical to FileTypeEQ.
func FileType(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldFileType, v))
}

// Extension applies equality check predicate on the "extension" field. It's identical to ExtensionEQ.
func Extension(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldExtension, v))
}

// FileSizeBytes applies equality check predicate on the "file_size_bytes" field. It's identical to FileSizeBytesEQ.
func FileSizeBytes(v int64) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldFileSizeBytes, v))
}

// StoragePath applies equality check predicate on the "storage_path" field. It's identical to StoragePathEQ.
func StoragePath(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldStoragePath, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldCreatedAt, v))
}

// IsCompressed applies equality check predicate on the "is_compressed" field. It's identical to IsCompressedEQ.
func IsCompressed(v bool) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldIsCompressed, v))
}

// OriginalPath applies equality check predicate on the "original_path" field. It's identical to OriginalPathEQ.
func OriginalPath(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldOriginalPath, v))
}

// CompressionRatio applies equality check predicate on the "compression_ratio" field. It's identical to CompressionRatioEQ.
func CompressionRatio(v float64) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldCompressionRatio, v))
}

// OriginalFilenameEQ applies the EQ predicate on the "original_filename" field.
func OriginalFilenameEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldOriginalFilename, v))
}

// OriginalFilenameNEQ applies the NEQ predicate on the "original_filename" field.
func OriginalFilenameNEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldOriginalFilename, v))
}

// OriginalFilenameIn applies the In predicate on the "original_filename" field.
func OriginalFilenameIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldOriginalFilename, vs...))
}

// OriginalFilenameNotIn applies the NotIn predicate on the "original_filename" field.
func OriginalFilenameNotIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldOriginalFilename, vs...))
}

// OriginalFilenameGT applies the GT predicate on the "original_filename" field.
func OriginalFilenameGT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldOriginalFilename, v))
}

// OriginalFilenameGTE applies the GTE predicate on the "original_filename" field.
func OriginalFilenameGTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldOriginalFilename, v))
}

// OriginalFilenameLT applies the LT predicate on the "original_filename" field.
func OriginalFilenameLT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldOriginalFilename, v))
}

// OriginalFilenameLTE applies the LTE predicate on the "original_filename" field.
func OriginalFilenameLTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldOriginalFilename, v))
}

// OriginalFilenameContains applies the Contains predicate on the "original_filename" field.
func OriginalFilenameContains(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContains(FieldOriginalFilename, v))
}

// OriginalFilenameHasPrefix applies the HasPrefix predicate on the "original_filename" field.
func OriginalFilenameHasPrefix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasPrefix(FieldOriginalFilename, v))
}

// OriginalFilenameHasSuffix applies the HasSuffix predicate on the "original_filename" field.
func OriginalFilenameHasSuffix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasSuffix(FieldOriginalFilename, v))
}

// OriginalFilenameEqualFold applies the EqualFold predicate on the "original_filename" field.
func OriginalFilenameEqualFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEqualFold(FieldOriginalFilename, v))
}

// OriginalFilenameContainsFold applies the ContainsFold predicate on the "original_filename" field.
func OriginalFilenameContainsFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContainsFold(FieldOriginalFilename, v))
}

// FileTypeEQ applies the EQ predicate on the "file_type" field.
func FileTypeEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldFileType, v))
}

// FileTypeNEQ applies the NEQ predicate on the "file_type" field.
func FileTypeNEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldFileType, v))
}

// FileTypeIn applies the In predicate on the "file_type" field.
func FileTypeIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldFileType, vs...))
}

// FileTypeNotIn applies the NotIn predicate on the "file_type" field.
func FileTypeNotIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldFileType, vs...))
}

// FileTypeGT applies the GT predicate on the "file_type" field.
func FileTypeGT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldFileType, v))
}

// FileTypeGTE applies the GTE predicate on the "file_type" field.
func FileTypeGTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldFileType, v))
}

// FileTypeLT applies the LT predicate on the "file_type" field.
func FileTypeLT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldFileType, v))
}

// FileTypeLTE applies the LTE predicate on the "file_type" field.
func FileTypeLTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldFileType, v))
}

// FileTypeContains applies the Contains predicate on the "file_type" field.
func FileTypeContains(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContains(FieldFileType, v))
}

// FileTypeHasPrefix applies the HasPrefix predicate on the "file_type" field.
func FileTypeHasPrefix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasPrefix(FieldFileType, v))
}

// FileTypeHasSuffix applies the HasSuffix predicate on the "file_type" field.
func FileTypeHasSuffix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasSuffix(FieldFileType, v))
}

// FileTypeEqualFold applies the EqualFold predicate on the "file_type" field.
func FileTypeEqualFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEqualFold(FieldFileType, v))
}

// FileTypeContainsFold applies the ContainsFold predicate on the "file_type" field.
func FileTypeContainsFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContainsFold(FieldFileType, v))
}

// ExtensionEQ applies the EQ predicate on the "extension" field.
func ExtensionEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldExtension, v))
}

// ExtensionNEQ applies the NEQ predicate on the "extension" field.
func ExtensionNEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldExtension, v))
}

// ExtensionIn applies the In predicate on the "extension" field.
func ExtensionIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldExtension, vs...))
}

// ExtensionNotIn applies the NotIn predicate on the "extension" field.
func ExtensionNotIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldExtension, vs...))
}

// ExtensionGT applies the GT predicate on the "extension" field.
func ExtensionGT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldExtension, v))
}

// ExtensionGTE applies the GTE predicate on the "extension" field.
func ExtensionGTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldExtension, v))
}

// ExtensionLT applies the LT predicate on the "extension" field.
func ExtensionLT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldExtension, v))
}

// ExtensionLTE applies the LTE predicate on the "extension" field.
func ExtensionLTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldExtension, v))
}

// ExtensionContains applies the Contains predicate on the "extension" field.
func ExtensionContains(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContains(FieldExtension, v))
}

// ExtensionHasPrefix applies the HasPrefix predicate on the "extension" field.
func ExtensionHasPrefix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasPrefix(FieldExtension, v))
}

// ExtensionHasSuffix applies the HasSuffix predicate on the "extension" field.
func ExtensionHasSuffix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasSuffix(FieldExtension, v))
}

// ExtensionEqualFold applies the EqualFold predicate on the "extension" field.
func ExtensionEqualFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEqualFold(FieldExtension, v))
}

// ExtensionContainsFold applies the ContainsFold predicate on the "extension" field.
func ExtensionContainsFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContainsFold(FieldExtension, v))
}

// FileSizeBytesEQ applies the EQ predicate on the "file_size_bytes" field.
func FileSizeBytesEQ(v int64) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldFileSizeBytes, v))
}

// FileSizeBytesNEQ applies the NEQ predicate on the "file_size_bytes" field.
func FileSizeBytesNEQ(v int64) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldFileSizeBytes, v))
}

// FileSizeBytesIn applies the In predicate on the "file_size_bytes" field.
func FileSizeBytesIn(vs ...int64) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldFileSizeBytes, vs...))
}

// FileSizeBytesNotIn applies the NotIn predicate on the "file_size_bytes" field.
func FileSizeBytesNotIn(vs ...int64) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldFileSizeBytes, vs...))
}

// FileSizeBytesGT applies the GT predicate on the "file_size_bytes" field.
func FileSizeBytesGT(v int64) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldFileSizeBytes, v))
}

// FileSizeBytesGTE applies the GTE predicate on the "file_size_bytes" field.
func FileSizeBytesGTE(v int64) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldFileSizeBytes, v))
}

// FileSizeBytesLT applies the LT predicate on the "file_size_bytes" field.
func FileSizeBytesLT(v int64) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldFileSizeBytes, v))
}

// FileSizeBytesLTE applies the LTE predicate on the "file_size_bytes" field.
func FileSizeBytesLTE(v int64) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldFileSizeBytes, v))
}

// StoragePathEQ applies the EQ predicate on the "storage_path" field.
func StoragePathEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldStoragePath, v))
}

// StoragePathNEQ applies the NEQ predicate on the "storage_path" field.
func StoragePathNEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldStoragePath, v))
}

// StoragePathIn applies the In predicate on the "storage_path" field.
func StoragePathIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldStoragePath, vs...))
}

// StoragePathNotIn applies the NotIn predicate on the "storage_path" field.
func StoragePathNotIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldStoragePath, vs...))
}

// StoragePathGT applies the GT predicate on the "storage_path" field.
func StoragePathGT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldStoragePath, v))
}

// StoragePathGTE applies the GTE predicate on the "storage_path" field.
func StoragePathGTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldStoragePath, v))
}

// StoragePathLT applies the LT predicate on the "storage_path" field.
func StoragePathLT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldStoragePath, v))
}

// StoragePathLTE applies the LTE predicate on the "storage_path" field.
func StoragePathLTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldStoragePath, v))
}

// StoragePathContains applies the Contains predicate on the "storage_path" field.
func StoragePathContains(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContains(FieldStoragePath, v))
}

// StoragePathHasPrefix applies the HasPrefix predicate on the "storage_path" field.
func StoragePathHasPrefix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasPrefix(FieldStoragePath, v))
}

// StoragePathHasSuffix applies the HasSuffix predicate on the "storage_path" field.
func StoragePathHasSuffix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasSuffix(FieldStoragePath, v))
}

// StoragePathEqualFold applies the EqualFold predicate on the "storage_path" field.
func StoragePathEqualFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEqualFold(FieldStoragePath, v))
}

// StoragePathContainsFold applies the ContainsFold predicate on the "storage_path" field.
func StoragePathContainsFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContainsFold(FieldStoragePath, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldCreatedAt, v))
}

// IsCompressedEQ applies the EQ predicate on the "is_compressed" field.
func IsCompressedEQ(v bool) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldIsCompressed, v))
}

// IsCompressedNEQ applies the NEQ predicate on the "is_compressed" field.
func IsCompressedNEQ(v bool) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldIsCompressed, v))
}

// OriginalPathEQ applies the EQ predicate on the "original_path" field.
func OriginalPathEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldOriginalPath, v))
}

// OriginalPathNEQ applies the NEQ predicate on the "original_path" field.
func OriginalPathNEQ(v string) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldOriginalPath, v))
}

// OriginalPathIn applies the In predicate on the "original_path" field.
func OriginalPathIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldOriginalPath, vs...))
}

// OriginalPathNotIn applies the NotIn predicate on the "original_path" field.
func OriginalPathNotIn(vs ...string) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldOriginalPath, vs...))
}

// OriginalPathGT applies the GT predicate on the "original_path" field.
func OriginalPathGT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldOriginalPath, v))
}

// OriginalPathGTE applies the GTE predicate on the "original_path" field.
func OriginalPathGTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldOriginalPath, v))
}

// OriginalPathLT applies the LT predicate on the "original_path" field.
func OriginalPathLT(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldOriginalPath, v))
}

// OriginalPathLTE applies the LTE predicate on the "original_path" field.
func OriginalPathLTE(v string) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldOriginalPath, v))
}

// OriginalPathContains applies the Contains predicate on the "original_path" field.
func OriginalPathContains(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContains(FieldOriginalPath, v))
}

// OriginalPathHasPrefix applies the HasPrefix predicate on the "original_path" field.
func OriginalPathHasPrefix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasPrefix(FieldOriginalPath, v))
}

// OriginalPathHasSuffix applies the HasSuffix predicate on the "original_path" field.
func OriginalPathHasSuffix(v string) predicate.Asset {
	return predicate.Asset(sql.FieldHasSuffix(FieldOriginalPath, v))
}

// OriginalPathIsNil applies the IsNil predicate on the "original_path" field.
func OriginalPathIsNil() predicate.Asset {
	return predicate.Asset(sql.FieldIsNull(FieldOriginalPath))
}

// OriginalPathNotNil applies the NotNil predicate on the "original_path" field.
func OriginalPathNotNil() predicate.Asset {
	return predicate.Asset(sql.FieldNotNull(FieldOriginalPath))
}

// OriginalPathEqualFold applies the EqualFold predicate on the "original_path" field.
func OriginalPathEqualFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldEqualFold(FieldOriginalPath, v))
}

// OriginalPathContainsFold applies the ContainsFold predicate on the "original_path" field.
func OriginalPathContainsFold(v string) predicate.Asset {
	return predicate.Asset(sql.FieldContainsFold(FieldOriginalPath, v))
}

// CompressionRatioEQ applies the EQ predicate on the "compression_ratio" field.
func CompressionRatioEQ(v float64) predicate.Asset {
	return predicate.Asset(sql.FieldEQ(FieldCompressionRatio, v))
}

// CompressionRatioNEQ applies the NEQ predicate on the "compression_ratio" field.
func CompressionRatioNEQ(v float64) predicate.Asset {
	return predicate.Asset(sql.FieldNEQ(FieldCompressionRatio, v))
}

// CompressionRatioIn applies the In predicate on the "compression_ratio" field.
func CompressionRatioIn(vs ...float64) predicate.Asset {
	return predicate.Asset(sql.FieldIn(FieldCompressionRatio, vs...))
}

// CompressionRatioNotIn applies the NotIn predicate on the "compression_ratio" field.
func CompressionRatioNotIn(vs ...float64) predicate.Asset {
	return predicate.Asset(sql.FieldNotIn(FieldCompressionRatio, vs...))
}

// CompressionRatioGT applies the GT predicate on the "compression_ratio" field.
func CompressionRatioGT(v float64) predicate.Asset {
	return predicate.Asset(sql.FieldGT(FieldCompressionRatio, v))
}

// CompressionRatioGTE applies the GTE predicate on the "compression_ratio" field.
func CompressionRatioGTE(v float64) predicate.Asset {
	return predicate.Asset(sql.FieldGTE(FieldCompressionRatio, v))
}

// CompressionRatioLT applies the LT predicate on the "compression_ratio" field.
func CompressionRatioLT(v float64) predicate.Asset {
	return predicate.Asset(sql.FieldLT(FieldCompressionRatio, v))
}

// CompressionRatioLTE applies the LTE predicate on the "compression_ratio" field.
func CompressionRatioLTE(v float64) predicate.Asset {
	return predicate.Asset(sql.FieldLTE(FieldCompressionRatio, v))
}

// CompressionRatioIsNil applies the IsNil predicate on the "compression_ratio" field.
func CompressionRatioIsNil() predicate.Asset {
	return predicate.Asset(sql.FieldIsNull(FieldCompressionRatio))
}

// CompressionRatioNotNil applies the NotNil predicate on the "compression_ratio" field.
func CompressionRatioNotNil() predicate.Asset {
	return predicate.Asset(sql.FieldNotNull(FieldCompressionRatio))
}

// HasTags applies the HasEdge predicate on the "tags" edge.
func HasTags() predicate.Asset {
	return predicate.Asset(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, TagsTable, TagsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTagsWith applies the HasEdge predicate on the "tags" edge with a given conditions (other predicates).
func HasTagsWith(preds ...predicate.Tag) predicate.Asset {
	return predicate.Asset(func(s *sql.Selector) {
		step := newTagsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCompressionJobs applies the HasEdge predicate on the "compression_jobs" edge.
func HasCompressionJobs() predicate.Asset {
	return predicate.Asset(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CompressionJobsTable, CompressionJobsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCompressionJobsWith applies the HasEdge predicate on the "compression_jobs" edge with a given conditions (other predicates).
func HasCompressionJobsWith(preds ...predicate.CompressionJob) predicate.Asset {
	return predicate.Asset(func(s *sql.Selector) {
		step := newCompressionJobsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Asset) predicate.Asset {
	return predicate.Asset(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Asset) predicate.Asset {
	return predicate.Asset(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Asset) predicate.Asset {
	return predicate.Asset(sql.NotPredicates(p))
}
