// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AssetsColumns holds the columns for the "assets" table.
	AssetsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "original_filename", Type: field.TypeString},
		{Name: "file_type", Type: field.TypeEnum, Enums: []string{"image", "document", "audio", "video", "other"}},
		{Name: "extension", Type: field.TypeString},
		{Name: "file_size_bytes", Type: field.TypeInt64},
		{Name: "storage_path", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// AssetsTable holds the schema information for the "assets" table.
	AssetsTable = &schema.Table{
		Name:       "assets",
		Columns:    AssetsColumns,
		PrimaryKey: []*schema.Column{AssetsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "asset_created_at",
				Unique:  false,
				Columns: []*schema.Column{AssetsColumns[6]},
			},
			{
				Name:    "asset_file_type",
				Unique:  false,
				Columns: []*schema.Column{AssetsColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AssetsTable,
	}
)

func init() {
}
