// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/adimail/asset-manager/ent/asset"
	"github.com/adimail/asset-manager/ent/compressionjob"
	"github.com/adimail/asset-manager/ent/predicate"
	"github.com/adimail/asset-manager/ent/tag"
)

// AssetUpdate is the builder for updating Asset entities.
type AssetUpdate struct {
	config
	hooks    []Hook
	mutation *AssetMutation
}

// Where appends a list predicates to the AssetUpdate builder.
func (_u *AssetUpdate) Where(ps ...predicate.Asset) *AssetUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOriginalFilename sets the "original_filename" field.
func (_u *AssetUpdate) SetOriginalFilename(v string) *AssetUpdate {
	_u.mutation.SetOriginalFilename(v)
	return _u
}

// SetNillableOriginalFilename sets the "original_filename" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableOriginalFilename(v *string) *AssetUpdate {
	if v != nil {
		_u.SetOriginalFilename(*v)
	}
	return _u
}

// SetFileType sets the "file_type" field.
func (_u *AssetUpdate) SetFileType(v string) *AssetUpdate {
	_u.mutation.SetFileType(v)
	return _u
}

// SetNillableFileType sets the "file_type" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableFileType(v *string) *AssetUpdate {
	if v != nil {
		_u.SetFileType(*v)
	}
	return _u
}

// SetExtension sets the "extension" field.
func (_u *AssetUpdate) SetExtension(v string) *AssetUpdate {
	_u.mutation.SetExtension(v)
	return _u
}

// SetNillableExtension sets the "extension" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableExtension(v *string) *AssetUpdate {
	if v != nil {
		_u.SetExtension(*v)
	}
	return _u
}

// SetFileSizeBytes sets the "file_size_bytes" field.
func (_u *AssetUpdate) SetFileSizeBytes(v int64) *AssetUpdate {
	_u.mutation.ResetFileSizeBytes()
	_u.mutation.SetFileSizeBytes(v)
	return _u
}

// SetNillableFileSizeBytes sets the "file_size_bytes" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableFileSizeBytes(v *int64) *AssetUpdate {
	if v != nil {
		_u.SetFileSizeBytes(*v)
	}
	return _u
}

// AddFileSizeBytes adds value to the "file_size_bytes" field.
func (_u *AssetUpdate) AddFileSizeBytes(v int64) *AssetUpdate {
	_u.mutation.AddFileSizeBytes(v)
	return _u
}

// SetStoragePath sets the "storage_path" field.
func (_u *AssetUpdate) SetStoragePath(v string) *AssetUpdate {
	_u.mutation.SetStoragePath(v)
	return _u
}

// SetNillableStoragePath sets the "storage_path" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableStoragePath(v *string) *AssetUpdate {
	if v != nil {
		_u.SetStoragePath(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AssetUpdate) SetCreatedAt(v time.Time) *AssetUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableCreatedAt(v *time.Time) *AssetUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetIsCompressed sets the "is_compressed" field.
func (_u *AssetUpdate) SetIsCompressed(v bool) *AssetUpdate {
	_u.mutation.SetIsCompressed(v)
	return _u
}

// SetNillableIsCompressed sets the "is_compressed" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableIsCompressed(v *bool) *AssetUpdate {
	if v != nil {
		_u.SetIsCompressed(*v)
	}
	return _u
}

// SetOriginalPath sets the "original_path" field.
func (_u *AssetUpdate) SetOriginalPath(v string) *AssetUpdate {
	_u.mutation.SetOriginalPath(v)
	return _u
}

// SetNillableOriginalPath sets the "original_path" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableOriginalPath(v *string) *AssetUpdate {
	if v != nil {
		_u.SetOriginalPath(*v)
	}
	return _u
}

// ClearOriginalPath clears the value of the "original_path" field.
func (_u *AssetUpdate) ClearOriginalPath() *AssetUpdate {
	_u.mutation.ClearOriginalPath()
	return _u
}

// SetCompressionRatio sets the "compression_ratio" field.
func (_u *AssetUpdate) SetCompressionRatio(v float64) *AssetUpdate {
	_u.mutation.ResetCompressionRatio()
	_u.mutation.SetCompressionRatio(v)
	return _u
}

// SetNillableCompressionRatio sets the "compression_ratio" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableCompressionRatio(v *float64) *AssetUpdate {
	if v != nil {
		_u.SetCompressionRatio(*v)
	}
	return _u
}

// AddCompressionRatio adds value to the "compression_ratio" field.
func (_u *AssetUpdate) AddCompressionRatio(v float64) *AssetUpdate {
	_u.mutation.AddCompressionRatio(v)
	return _u
}

// ClearCompressionRatio clears the value of the "compression_ratio" field.
func (_u *AssetUpdate) ClearCompressionRatio() *AssetUpdate {
	_u.mutation.ClearCompressionRatio()
	return _u
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (_u *AssetUpdate) AddTagIDs(ids ...string) *AssetUpdate {
	_u.mutation.AddTagIDs(ids...)
	return _u
}

// AddTags adds the "tags" edges to the Tag entity.
func (_u *AssetUpdate) AddTags(v ...*Tag) *AssetUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTagIDs(ids...)
}

// AddCompressionJobIDs adds the "compression_jobs" edge to the CompressionJob entity by IDs.
func (_u *AssetUpdate) AddCompressionJobIDs(ids ...string) *AssetUpdate {
	_u.mutation.AddCompressionJobIDs(ids...)
	return _u
}

// AddCompressionJobs adds the "compression_jobs" edges to the CompressionJob entity.
func (_u *AssetUpdate) AddCompressionJobs(v ...*CompressionJob) *AssetUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCompressionJobIDs(ids...)
}

// Mutation returns the AssetMutation object of the builder.
func (_u *AssetUpdate) Mutation() *AssetMutation {
	return _u.mutation
}

// ClearTags clears all "tags" edges to the Tag entity.
func (_u *AssetUpdate) ClearTags() *AssetUpdate {
	_u.mutation.ClearTags()
	return _u
}

// RemoveTagIDs removes the "tags" edge to Tag entities by IDs.
func (_u *AssetUpdate) RemoveTagIDs(ids ...string) *AssetUpdate {
	_u.mutation.RemoveTagIDs(ids...)
	return _u
}

// RemoveTags removes "tags" edges to Tag entities.
func (_u *AssetUpdate) RemoveTags(v ...*Tag) *AssetUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTagIDs(ids...)
}

// ClearCompressionJobs clears all "compression_jobs" edges to the CompressionJob entity.
func (_u *AssetUpdate) ClearCompressionJobs() *AssetUpdate {
	_u.mutation.ClearCompressionJobs()
	return _u
}

// RemoveCompressionJobIDs removes the "compression_jobs" edge to CompressionJob entities by IDs.
func (_u *AssetUpdate) RemoveCompressionJobIDs(ids ...string) *AssetUpdate {
	_u.mutation.RemoveCompressionJobIDs(ids...)
	return _u
}

// RemoveCompressionJobs removes "compression_jobs" edges to CompressionJob entities.
func (_u *AssetUpdate) RemoveCompressionJobs(v ...*CompressionJob) *AssetUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCompressionJobIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AssetUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AssetUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AssetUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AssetUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AssetUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(asset.Table, asset.Columns, sqlgraph.NewFieldSpec(asset.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OriginalFilename(); ok {
		_spec.SetField(asset.FieldOriginalFilename, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileType(); ok {
		_spec.SetField(asset.FieldFileType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Extension(); ok {
		_spec.SetField(asset.FieldExtension, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileSizeBytes(); ok {
		_spec.SetField(asset.FieldFileSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSizeBytes(); ok {
		_spec.AddField(asset.FieldFileSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.StoragePath(); ok {
		_spec.SetField(asset.FieldStoragePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(asset.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsCompressed(); ok {
		_spec.SetField(asset.FieldIsCompressed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.OriginalPath(); ok {
		_spec.SetField(asset.FieldOriginalPath, field.TypeString, value)
	}
	if _u.mutation.OriginalPathCleared() {
		_spec.ClearField(asset.FieldOriginalPath, field.TypeString)
	}
	if value, ok := _u.mutation.CompressionRatio(); ok {
		_spec.SetField(asset.FieldCompressionRatio, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCompressionRatio(); ok {
		_spec.AddField(asset.FieldCompressionRatio, field.TypeFloat64, value)
	}
	if _u.mutation.CompressionRatioCleared() {
		_spec.ClearField(asset.FieldCompressionRatio, field.TypeFloat64)
	}
	if _u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   asset.TagsTable,
			Columns: asset.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTagsIDs(); len(nodes) > 0 && !_u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   asset.TagsTable,
			Columns: asset.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   asset.TagsTable,
			Columns: asset.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CompressionJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.CompressionJobsTable,
			Columns: []string{asset.CompressionJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(compressionjob.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCompressionJobsIDs(); len(nodes) > 0 && !_u.mutation.CompressionJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.CompressionJobsTable,
			Columns: []string{asset.CompressionJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(compressionjob.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CompressionJobsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.CompressionJobsTable,
			Columns: []string{asset.CompressionJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(compressionjob.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{asset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AssetUpdateOne is the builder for updating a single Asset entity.
type AssetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AssetMutation
}

// SetOriginalFilename sets the "original_filename" field.
func (_u *AssetUpdateOne) SetOriginalFilename(v string) *AssetUpdateOne {
	_u.mutation.SetOriginalFilename(v)
	return _u
}

// SetNillableOriginalFilename sets the "original_filename" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableOriginalFilename(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetOriginalFilename(*v)
	}
	return _u
}

// SetFileType sets the "file_type" field.
func (_u *AssetUpdateOne) SetFileType(v string) *AssetUpdateOne {
	_u.mutation.SetFileType(v)
	return _u
}

// SetNillableFileType sets the "file_type" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableFileType(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetFileType(*v)
	}
	return _u
}

// SetExtension sets the "extension" field.
func (_u *AssetUpdateOne) SetExtension(v string) *AssetUpdateOne {
	_u.mutation.SetExtension(v)
	return _u
}

// SetNillableExtension sets the "extension" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableExtension(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetExtension(*v)
	}
	return _u
}

// SetFileSizeBytes sets the "file_size_bytes" field.
func (_u *AssetUpdateOne) SetFileSizeBytes(v int64) *AssetUpdateOne {
	_u.mutation.ResetFileSizeBytes()
	_u.mutation.SetFileSizeBytes(v)
	return _u
}

// SetNillableFileSizeBytes sets the "file_size_bytes" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableFileSizeBytes(v *int64) *AssetUpdateOne {
	if v != nil {
		_u.SetFileSizeBytes(*v)
	}
	return _u
}

// AddFileSizeBytes adds value to the "file_size_bytes" field.
func (_u *AssetUpdateOne) AddFileSizeBytes(v int64) *AssetUpdateOne {
	_u.mutation.AddFileSizeBytes(v)
	return _u
}

// SetStoragePath sets the "storage_path" field.
func (_u *AssetUpdateOne) SetStoragePath(v string) *AssetUpdateOne {
	_u.mutation.SetStoragePath(v)
	return _u
}

// SetNillableStoragePath sets the "storage_path" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableStoragePath(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetStoragePath(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AssetUpdateOne) SetCreatedAt(v time.Time) *AssetUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableCreatedAt(v *time.Time) *AssetUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetIsCompressed sets the "is_compressed" field.
func (_u *AssetUpdateOne) SetIsCompressed(v bool) *AssetUpdateOne {
	_u.mutation.SetIsCompressed(v)
	return _u
}

// SetNillableIsCompressed sets the "is_compressed" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableIsCompressed(v *bool) *AssetUpdateOne {
	if v != nil {
		_u.SetIsCompressed(*v)
	}
	return _u
}

// SetOriginalPath sets the "original_path" field.
func (_u *AssetUpdateOne) SetOriginalPath(v string) *AssetUpdateOne {
	_u.mutation.SetOriginalPath(v)
	return _u
}

// SetNillableOriginalPath sets the "original_path" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableOriginalPath(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetOriginalPath(*v)
	}
	return _u
}

// ClearOriginalPath clears the value of the "original_path" field.
func (_u *AssetUpdateOne) ClearOriginalPath() *AssetUpdateOne {
	_u.mutation.ClearOriginalPath()
	return _u
}

// SetCompressionRatio sets the "compression_ratio" field.
func (_u *AssetUpdateOne) SetCompressionRatio(v float64) *AssetUpdateOne {
	_u.mutation.ResetCompressionRatio()
	_u.mutation.SetCompressionRatio(v)
	return _u
}

// SetNillableCompressionRatio sets the "compression_ratio" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableCompressionRatio(v *float64) *AssetUpdateOne {
	if v != nil {
		_u.SetCompressionRatio(*v)
	}
	return _u
}

// AddCompressionRatio adds value to the "compression_ratio" field.
func (_u *AssetUpdateOne) AddCompressionRatio(v float64) *AssetUpdateOne {
	_u.mutation.AddCompressionRatio(v)
	return _u
}

// ClearCompressionRatio clears the value of the "compression_ratio" field.
func (_u *AssetUpdateOne) ClearCompressionRatio() *AssetUpdateOne {
	_u.mutation.ClearCompressionRatio()
	return _u
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (_u *AssetUpdateOne) AddTagIDs(ids ...string) *AssetUpdateOne {
	_u.mutation.AddTagIDs(ids...)
	return _u
}

// AddTags adds the "tags" edges to the Tag entity.
func (_u *AssetUpdateOne) AddTags(v ...*Tag) *AssetUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTagIDs(ids...)
}

// AddCompressionJobIDs adds the "compression_jobs" edge to the CompressionJob entity by IDs.
func (_u *AssetUpdateOne) AddCompressionJobIDs(ids ...string) *AssetUpdateOne {
	_u.mutation.AddCompressionJobIDs(ids...)
	return _u
}

// AddCompressionJobs adds the "compression_jobs" edges to the CompressionJob entity.
func (_u *AssetUpdateOne) AddCompressionJobs(v ...*CompressionJob) *AssetUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCompressionJobIDs(ids...)
}

// Mutation returns the AssetMutation object of the builder.
func (_u *AssetUpdateOne) Mutation() *AssetMutation {
	return _u.mutation
}

// ClearTags clears all "tags" edges to the Tag entity.
func (_u *AssetUpdateOne) ClearTags() *AssetUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// RemoveTagIDs removes the "tags" edge to Tag entities by IDs.
func (_u *AssetUpdateOne) RemoveTagIDs(ids ...string) *AssetUpdateOne {
	_u.mutation.RemoveTagIDs(ids...)
	return _u
}

// RemoveTags removes "tags" edges to Tag entities.
func (_u *AssetUpdateOne) RemoveTags(v ...*Tag) *AssetUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTagIDs(ids...)
}

// ClearCompressionJobs clears all "compression_jobs" edges to the CompressionJob entity.
func (_u *AssetUpdateOne) ClearCompressionJobs() *AssetUpdateOne {
	_u.mutation.ClearCompressionJobs()
	return _u
}

// RemoveCompressionJobIDs removes the "compression_jobs" edge to CompressionJob entities by IDs.
func (_u *AssetUpdateOne) RemoveCompressionJobIDs(ids ...string) *AssetUpdateOne {
	_u.mutation.RemoveCompressionJobIDs(ids...)
	return _u
}

// RemoveCompressionJobs removes "compression_jobs" edges to CompressionJob entities.
func (_u *AssetUpdateOne) RemoveCompressionJobs(v ...*CompressionJob) *AssetUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCompressionJobIDs(ids...)
}

// Where appends a list predicates to the AssetUpdate builder.
func (_u *AssetUpdateOne) Where(ps ...predicate.Asset) *AssetUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AssetUpdateOne) Select(field string, fields ...string) *AssetUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Asset entity.
func (_u *AssetUpdateOne) Save(ctx context.Context) (*Asset, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AssetUpdateOne) SaveX(ctx context.Context) *Asset {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AssetUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AssetUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AssetUpdateOne) sqlSave(ctx context.Context) (_node *Asset, err error) {
	_spec := sqlgraph.NewUpdateSpec(asset.Table, asset.Columns, sqlgraph.NewFieldSpec(asset.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Asset.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, asset.FieldID)
		for _, f := range fields {
			if !asset.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != asset.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OriginalFilename(); ok {
		_spec.SetField(asset.FieldOriginalFilename, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileType(); ok {
		_spec.SetField(asset.FieldFileType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Extension(); ok {
		_spec.SetField(asset.FieldExtension, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileSizeBytes(); ok {
		_spec.SetField(asset.FieldFileSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSizeBytes(); ok {
		_spec.AddField(asset.FieldFileSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.StoragePath(); ok {
		_spec.SetField(asset.FieldStoragePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(asset.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsCompressed(); ok {
		_spec.SetField(asset.FieldIsCompressed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.OriginalPath(); ok {
		_spec.SetField(asset.FieldOriginalPath, field.TypeString, value)
	}
	if _u.mutation.OriginalPathCleared() {
		_spec.ClearField(asset.FieldOriginalPath, field.TypeString)
	}
	if value, ok := _u.mutation.CompressionRatio(); ok {
		_spec.SetField(asset.FieldCompressionRatio, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCompressionRatio(); ok {
		_spec.AddField(asset.FieldCompressionRatio, field.TypeFloat64, value)
	}
	if _u.mutation.CompressionRatioCleared() {
		_spec.ClearField(asset.FieldCompressionRatio, field.TypeFloat64)
	}
	if _u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   asset.TagsTable,
			Columns: asset.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTagsIDs(); len(nodes) > 0 && !_u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   asset.TagsTable,
			Columns: asset.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   asset.TagsTable,
			Columns: asset.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CompressionJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.CompressionJobsTable,
			Columns: []string{asset.CompressionJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(compressionjob.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCompressionJobsIDs(); len(nodes) > 0 && !_u.mutation.CompressionJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.CompressionJobsTable,
			Columns: []string{asset.CompressionJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(compressionjob.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CompressionJobsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.CompressionJobsTable,
			Columns: []string{asset.CompressionJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(compressionjob.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Asset{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{asset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
