// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/adimail/asset-manager/ent/asset"
	"github.com/adimail/asset-manager/ent/predicate"
)

// AssetUpdate is the builder for updating Asset entities.
type AssetUpdate struct {
	config
	hooks    []Hook
	mutation *AssetMutation
}

// Where appends a list predicates to the AssetUpdate builder.
func (_u *AssetUpdate) Where(ps ...predicate.Asset) *AssetUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOriginalFilename sets the "original_filename" field.
func (_u *AssetUpdate) SetOriginalFilename(v string) *AssetUpdate {
	_u.mutation.SetOriginalFilename(v)
	return _u
}

// SetNillableOriginalFilename sets the "original_filename" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableOriginalFilename(v *string) *AssetUpdate {
	if v != nil {
		_u.SetOriginalFilename(*v)
	}
	return _u
}

// SetFileType sets the "file_type" field.
func (_u *AssetUpdate) SetFileType(v asset.FileType) *AssetUpdate {
	_u.mutation.SetFileType(v)
	return _u
}

// SetNillableFileType sets the "file_type" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableFileType(v *asset.FileType) *AssetUpdate {
	if v != nil {
		_u.SetFileType(*v)
	}
	return _u
}

// SetExtension sets the "extension" field.
func (_u *AssetUpdate) SetExtension(v string) *AssetUpdate {
	_u.mutation.SetExtension(v)
	return _u
}

// SetNillableExtension sets the "extension" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableExtension(v *string) *AssetUpdate {
	if v != nil {
		_u.SetExtension(*v)
	}
	return _u
}

// SetFileSizeBytes sets the "file_size_bytes" field.
func (_u *AssetUpdate) SetFileSizeBytes(v int64) *AssetUpdate {
	_u.mutation.ResetFileSizeBytes()
	_u.mutation.SetFileSizeBytes(v)
	return _u
}

// SetNillableFileSizeBytes sets the "file_size_bytes" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableFileSizeBytes(v *int64) *AssetUpdate {
	if v != nil {
		_u.SetFileSizeBytes(*v)
	}
	return _u
}

// AddFileSizeBytes adds value to the "file_size_bytes" field.
func (_u *AssetUpdate) AddFileSizeBytes(v int64) *AssetUpdate {
	_u.mutation.AddFileSizeBytes(v)
	return _u
}

// SetStoragePath sets the "storage_path" field.
func (_u *AssetUpdate) SetStoragePath(v string) *AssetUpdate {
	_u.mutation.SetStoragePath(v)
	return _u
}

// SetNillableStoragePath sets the "storage_path" field if the given value is not nil.
func (_u *AssetUpdate) SetNillableStoragePath(v *string) *AssetUpdate {
	if v != nil {
		_u.SetStoragePath(*v)
	}
	return _u
}

// Mutation returns the AssetMutation object of the builder.
func (_u *AssetUpdate) Mutation() *AssetMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AssetUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AssetUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AssetUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AssetUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AssetUpdate) check() error {
	if v, ok := _u.mutation.OriginalFilename(); ok {
		if err := asset.OriginalFilenameValidator(v); err != nil {
			return &ValidationError{Name: "original_filename", err: fmt.Errorf(`ent: validator failed for field "Asset.original_filename": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileType(); ok {
		if err := asset.FileTypeValidator(v); err != nil {
			return &ValidationError{Name: "file_type", err: fmt.Errorf(`ent: validator failed for field "Asset.file_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileSizeBytes(); ok {
		if err := asset.FileSizeBytesValidator(v); err != nil {
			return &ValidationError{Name: "file_size_bytes", err: fmt.Errorf(`ent: validator failed for field "Asset.file_size_bytes": %w`, err)}
		}
	}
	return nil
}

func (_u *AssetUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(asset.Table, asset.Columns, sqlgraph.NewFieldSpec(asset.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OriginalFilename(); ok {
		_spec.SetField(asset.FieldOriginalFilename, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileType(); ok {
		_spec.SetField(asset.FieldFileType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Extension(); ok {
		_spec.SetField(asset.FieldExtension, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileSizeBytes(); ok {
		_spec.SetField(asset.FieldFileSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSizeBytes(); ok {
		_spec.AddField(asset.FieldFileSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.StoragePath(); ok {
		_spec.SetField(asset.FieldStoragePath, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{asset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AssetUpdateOne is the builder for updating a single Asset entity.
type AssetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AssetMutation
}

// SetOriginalFilename sets the "original_filename" field.
func (_u *AssetUpdateOne) SetOriginalFilename(v string) *AssetUpdateOne {
	_u.mutation.SetOriginalFilename(v)
	return _u
}

// SetNillableOriginalFilename sets the "original_filename" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableOriginalFilename(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetOriginalFilename(*v)
	}
	return _u
}

// SetFileType sets the "file_type" field.
func (_u *AssetUpdateOne) SetFileType(v asset.FileType) *AssetUpdateOne {
	_u.mutation.SetFileType(v)
	return _u
}

// SetNillableFileType sets the "file_type" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableFileType(v *asset.FileType) *AssetUpdateOne {
	if v != nil {
		_u.SetFileType(*v)
	}
	return _u
}

// SetExtension sets the "extension" field.
func (_u *AssetUpdateOne) SetExtension(v string) *AssetUpdateOne {
	_u.mutation.SetExtension(v)
	return _u
}

// SetNillableExtension sets the "extension" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableExtension(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetExtension(*v)
	}
	return _u
}

// SetFileSizeBytes sets the "file_size_bytes" field.
func (_u *AssetUpdateOne) SetFileSizeBytes(v int64) *AssetUpdateOne {
	_u.mutation.ResetFileSizeBytes()
	_u.mutation.SetFileSizeBytes(v)
	return _u
}

// SetNillableFileSizeBytes sets the "file_size_bytes" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableFileSizeBytes(v *int64) *AssetUpdateOne {
	if v != nil {
		_u.SetFileSizeBytes(*v)
	}
	return _u
}

// AddFileSizeBytes adds value to the "file_size_bytes" field.
func (_u *AssetUpdateOne) AddFileSizeBytes(v int64) *AssetUpdateOne {
	_u.mutation.AddFileSizeBytes(v)
	return _u
}

// SetStoragePath sets the "storage_path" field.
func (_u *AssetUpdateOne) SetStoragePath(v string) *AssetUpdateOne {
	_u.mutation.SetStoragePath(v)
	return _u
}

// SetNillableStoragePath sets the "storage_path" field if the given value is not nil.
func (_u *AssetUpdateOne) SetNillableStoragePath(v *string) *AssetUpdateOne {
	if v != nil {
		_u.SetStoragePath(*v)
	}
	return _u
}

// Mutation returns the AssetMutation object of the builder.
func (_u *AssetUpdateOne) Mutation() *AssetMutation {
	return _u.mutation
}

// Where appends a list predicates to the AssetUpdate builder.
func (_u *AssetUpdateOne) Where(ps ...predicate.Asset) *AssetUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AssetUpdateOne) Select(field string, fields ...string) *AssetUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Asset entity.
func (_u *AssetUpdateOne) Save(ctx context.Context) (*Asset, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AssetUpdateOne) SaveX(ctx context.Context) *Asset {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AssetUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AssetUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AssetUpdateOne) check() error {
	if v, ok := _u.mutation.OriginalFilename(); ok {
		if err := asset.OriginalFilenameValidator(v); err != nil {
			return &ValidationError{Name: "original_filename", err: fmt.Errorf(`ent: validator failed for field "Asset.original_filename": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileType(); ok {
		if err := asset.FileTypeValidator(v); err != nil {
			return &ValidationError{Name: "file_type", err: fmt.Errorf(`ent: validator failed for field "Asset.file_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileSizeBytes(); ok {
		if err := asset.FileSizeBytesValidator(v); err != nil {
			return &ValidationError{Name: "file_size_bytes", err: fmt.Errorf(`ent: validator failed for field "Asset.file_size_bytes": %w`, err)}
		}
	}
	return nil
}

func (_u *AssetUpdateOne) sqlSave(ctx context.Context) (_node *Asset, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(asset.Table, asset.Columns, sqlgraph.NewFieldSpec(asset.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Asset.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, asset.FieldID)
		for _, f := range fields {
			if !asset.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != asset.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OriginalFilename(); ok {
		_spec.SetField(asset.FieldOriginalFilename, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileType(); ok {
		_spec.SetField(asset.FieldFileType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Extension(); ok {
		_spec.SetField(asset.FieldExtension, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileSizeBytes(); ok {
		_spec.SetField(asset.FieldFileSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSizeBytes(); ok {
		_spec.AddField(asset.FieldFileSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.StoragePath(); ok {
		_spec.SetField(asset.FieldStoragePath, field.TypeString, value)
	}
	_node = &Asset{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{asset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
