// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/adimail/asset-manager/ent/asset"
	"github.com/adimail/asset-manager/ent/compressionjob"
	"github.com/adimail/asset-manager/ent/tag"
)

// AssetCreate is the builder for creating a Asset entity.
type AssetCreate struct {
	config
	mutation *AssetMutation
	hooks    []Hook
}

// SetOriginalFilename sets the "original_filename" field.
func (_c *AssetCreate) SetOriginalFilename(v string) *AssetCreate {
	_c.mutation.SetOriginalFilename(v)
	return _c
}

// SetFileType sets the "file_type" field.
func (_c *AssetCreate) SetFileType(v string) *AssetCreate {
	_c.mutation.SetFileType(v)
	return _c
}

// SetExtension sets the "extension" field.
func (_c *AssetCreate) SetExtension(v string) *AssetCreate {
	_c.mutation.SetExtension(v)
	return _c
}

// SetFileSizeBytes sets the "file_size_bytes" field.
func (_c *AssetCreate) SetFileSizeBytes(v int64) *AssetCreate {
	_c.mutation.SetFileSizeBytes(v)
	return _c
}

// SetStoragePath sets the "storage_path" field.
func (_c *AssetCreate) SetStoragePath(v string) *AssetCreate {
	_c.mutation.SetStoragePath(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AssetCreate) SetCreatedAt(v time.Time) *AssetCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AssetCreate) SetNillableCreatedAt(v *time.Time) *AssetCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetIsCompressed sets the "is_compressed" field.
func (_c *AssetCreate) SetIsCompressed(v bool) *AssetCreate {
	_c.mutation.SetIsCompressed(v)
	return _c
}

// SetNillableIsCompressed sets the "is_compressed" field if the given value is not nil.
func (_c *AssetCreate) SetNillableIsCompressed(v *bool) *AssetCreate {
	if v != nil {
		_c.SetIsCompressed(*v)
	}
	return _c
}

// SetOriginalPath sets the "original_path" field.
func (_c *AssetCreate) SetOriginalPath(v string) *AssetCreate {
	_c.mutation.SetOriginalPath(v)
	return _c
}

// SetNillableOriginalPath sets the "original_path" field if the given value is not nil.
func (_c *AssetCreate) SetNillableOriginalPath(v *string) *AssetCreate {
	if v != nil {
		_c.SetOriginalPath(*v)
	}
	return _c
}

// SetCompressionRatio sets the "compression_ratio" field.
func (_c *AssetCreate) SetCompressionRatio(v float64) *AssetCreate {
	_c.mutation.SetCompressionRatio(v)
	return _c
}

// SetNillableCompressionRatio sets the "compression_ratio" field if the given value is not nil.
func (_c *AssetCreate) SetNillableCompressionRatio(v *float64) *AssetCreate {
	if v != nil {
		_c.SetCompressionRatio(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AssetCreate) SetID(v string) *AssetCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AssetCreate) SetNillableID(v *string) *AssetCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (_c *AssetCreate) AddTagIDs(ids ...string) *AssetCreate {
	_c.mutation.AddTagIDs(ids...)
	return _c
}

// AddTags adds the "tags" edges to the Tag entity.
func (_c *AssetCreate) AddTags(v ...*Tag) *AssetCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTagIDs(ids...)
}

// AddCompressionJobIDs adds the "compression_jobs" edge to the CompressionJob entity by IDs.
func (_c *AssetCreate) AddCompressionJobIDs(ids ...string) *AssetCreate {
	_c.mutation.AddCompressionJobIDs(ids...)
	return _c
}

// AddCompressionJobs adds the "compression_jobs" edges to the CompressionJob entity.
func (_c *AssetCreate) AddCompressionJobs(v ...*CompressionJob) *AssetCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCompressionJobIDs(ids...)
}

// Mutation returns the AssetMutation object of the builder.
func (_c *AssetCreate) Mutation() *AssetMutation {
	return _c.mutation
}

// Save creates the Asset in the database.
func (_c *AssetCreate) Save(ctx context.Context) (*Asset, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AssetCreate) SaveX(ctx context.Context) *Asset {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AssetCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AssetCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AssetCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := asset.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.IsCompressed(); !ok {
		v := asset.DefaultIsCompressed
		_c.mutation.SetIsCompressed(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := asset.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AssetCreate) check() error {
	if _, ok := _c.mutation.OriginalFilename(); !ok {
		return &ValidationError{Name: "original_filename", err: errors.New(`ent: missing required field "Asset.original_filename"`)}
	}
	if _, ok := _c.mutation.FileType(); !ok {
		return &ValidationError{Name: "file_type", err: errors.New(`ent: missing required field "Asset.file_type"`)}
	}
	if _, ok := _c.mutation.Extension(); !ok {
		return &ValidationError{Name: "extension", err: errors.New(`ent: missing required field "Asset.extension"`)}
	}
	if _, ok := _c.mutation.FileSizeBytes(); !ok {
		return &ValidationError{Name: "file_size_bytes", err: errors.New(`ent: missing required field "Asset.file_size_bytes"`)}
	}
	if _, ok := _c.mutation.StoragePath(); !ok {
		return &ValidationError{Name: "storage_path", err: errors.New(`ent: missing required field "Asset.storage_path"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Asset.created_at"`)}
	}
	if _, ok := _c.mutation.IsCompressed(); !ok {
		return &ValidationError{Name: "is_compressed", err: errors.New(`ent: missing required field "Asset.is_compressed"`)}
	}
	return nil
}

func (_c *AssetCreate) sqlSave(ctx context.Context) (*Asset, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Asset.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AssetCreate) createSpec() (*Asset, *sqlgraph.CreateSpec) {
	var (
		_node = &Asset{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(asset.Table, sqlgraph.NewFieldSpec(asset.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.OriginalFilename(); ok {
		_spec.SetField(asset.FieldOriginalFilename, field.TypeString, value)
		_node.OriginalFilename = value
	}
	if value, ok := _c.mutation.FileType(); ok {
		_spec.SetField(asset.FieldFileType, field.TypeString, value)
		_node.FileType = value
	}
	if value, ok := _c.mutation.Extension(); ok {
		_spec.SetField(asset.FieldExtension, field.TypeString, value)
		_node.Extension = value
	}
	if value, ok := _c.mutation.FileSizeBytes(); ok {
		_spec.SetField(asset.FieldFileSizeBytes, field.TypeInt64, value)
		_node.FileSizeBytes = value
	}
	if value, ok := _c.mutation.StoragePath(); ok {
		_spec.SetField(asset.FieldStoragePath, field.TypeString, value)
		_node.StoragePath = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(asset.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.IsCompressed(); ok {
		_spec.SetField(asset.FieldIsCompressed, field.TypeBool, value)
		_node.IsCompressed = value
	}
	if value, ok := _c.mutation.OriginalPath(); ok {
		_spec.SetField(asset.FieldOriginalPath, field.TypeString, value)
		_node.OriginalPath = value
	}
	if value, ok := _c.mutation.CompressionRatio(); ok {
		_spec.SetField(asset.FieldCompressionRatio, field.TypeFloat64, value)
		_node.CompressionRatio = value
	}
	if nodes := _c.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   asset.TagsTable,
			Columns: asset.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CompressionJobsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   asset.CompressionJobsTable,
			Columns: []string{asset.CompressionJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(compressionjob.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AssetCreateBulk is the builder for creating many Asset entities in bulk.
type AssetCreateBulk struct {
	config
	err      error
	builders []*AssetCreate
}

// Save creates the Asset entities in the database.
func (_c *AssetCreateBulk) Save(ctx context.Context) ([]*Asset, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Asset, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AssetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AssetCreateBulk) SaveX(ctx context.Context) []*Asset {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AssetCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AssetCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
