// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/adimail/asset-manager/ent/asset"
	"github.com/adimail/asset-manager/ent/compressionjob"
)

// CompressionJob is the model entity for the CompressionJob schema.
type CompressionJob struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Progress holds the value of the "progress" field.
	Progress int `json:"progress,omitempty"`
	// Error holds the value of the "error" field.
	Error string `json:"error,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt time.Time `json:"started_at,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt time.Time `json:"completed_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CompressionJobQuery when eager-loading is set.
	Edges                  CompressionJobEdges `json:"edges"`
	asset_compression_jobs *string
	selectValues           sql.SelectValues
}

// CompressionJobEdges holds the relations/edges for other nodes in the graph.
type CompressionJobEdges struct {
	// Asset holds the value of the asset edge.
	Asset *Asset `json:"asset,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AssetOrErr returns the Asset value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CompressionJobEdges) AssetOrErr() (*Asset, error) {
	if e.Asset != nil {
		return e.Asset, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: asset.Label}
	}
	return nil, &NotLoadedError{edge: "asset"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CompressionJob) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case compressionjob.FieldProgress:
			values[i] = new(sql.NullInt64)
		case compressionjob.FieldID, compressionjob.FieldStatus, compressionjob.FieldError:
			values[i] = new(sql.NullString)
		case compressionjob.FieldStartedAt, compressionjob.FieldCompletedAt:
			values[i] = new(sql.NullTime)
		case compressionjob.ForeignKeys[0]: // asset_compression_jobs
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CompressionJob fields.
func (_m *CompressionJob) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case compressionjob.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case compressionjob.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case compressionjob.FieldProgress:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field progress", values[i])
			} else if value.Valid {
				_m.Progress = int(value.Int64)
			}
		case compressionjob.FieldError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error", values[i])
			} else if value.Valid {
				_m.Error = value.String
			}
		case compressionjob.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		case compressionjob.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = value.Time
			}
		case compressionjob.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field asset_compression_jobs", values[i])
			} else if value.Valid {
				_m.asset_compression_jobs = new(string)
				*_m.asset_compression_jobs = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CompressionJob.
// This includes values selected through modifiers, order, etc.
func (_m *CompressionJob) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAsset queries the "asset" edge of the CompressionJob entity.
func (_m *CompressionJob) QueryAsset() *AssetQuery {
	return NewCompressionJobClient(_m.config).QueryAsset(_m)
}

// Update returns a builder for updating this CompressionJob.
// Note that you need to call CompressionJob.Unwrap() before calling this method if this CompressionJob
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CompressionJob) Update() *CompressionJobUpdateOne {
	return NewCompressionJobClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CompressionJob entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CompressionJob) Unwrap() *CompressionJob {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CompressionJob is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CompressionJob) String() string {
	var builder strings.Builder
	builder.WriteString("CompressionJob(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("progress=")
	builder.WriteString(fmt.Sprintf("%v", _m.Progress))
	builder.WriteString(", ")
	builder.WriteString("error=")
	builder.WriteString(_m.Error)
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("completed_at=")
	builder.WriteString(_m.CompletedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CompressionJobs is a parsable slice of CompressionJob.
type CompressionJobs []*CompressionJob
