// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/adimail/asset-manager/ent/compressionjob"
	"github.com/adimail/asset-manager/ent/predicate"
)

// CompressionJobDelete is the builder for deleting a CompressionJob entity.
type CompressionJobDelete struct {
	config
	hooks    []Hook
	mutation *CompressionJobMutation
}

// Where appends a list predicates to the CompressionJobDelete builder.
func (_d *CompressionJobDelete) Where(ps ...predicate.CompressionJob) *CompressionJobDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CompressionJobDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CompressionJobDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CompressionJobDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(compressionjob.Table, sqlgraph.NewFieldSpec(compressionjob.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CompressionJobDeleteOne is the builder for deleting a single CompressionJob entity.
type CompressionJobDeleteOne struct {
	_d *CompressionJobDelete
}

// Where appends a list predicates to the CompressionJobDelete builder.
func (_d *CompressionJobDeleteOne) Where(ps ...predicate.CompressionJob) *CompressionJobDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CompressionJobDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{compressionjob.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CompressionJobDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
