// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/adimail/asset-manager/ent/asset"
	"github.com/adimail/asset-manager/ent/compressionjob"
)

// CompressionJobCreate is the builder for creating a CompressionJob entity.
type CompressionJobCreate struct {
	config
	mutation *CompressionJobMutation
	hooks    []Hook
}

// SetStatus sets the "status" field.
func (_c *CompressionJobCreate) SetStatus(v string) *CompressionJobCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *CompressionJobCreate) SetNillableStatus(v *string) *CompressionJobCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetProgress sets the "progress" field.
func (_c *CompressionJobCreate) SetProgress(v int) *CompressionJobCreate {
	_c.mutation.SetProgress(v)
	return _c
}

// SetNillableProgress sets the "progress" field if the given value is not nil.
func (_c *CompressionJobCreate) SetNillableProgress(v *int) *CompressionJobCreate {
	if v != nil {
		_c.SetProgress(*v)
	}
	return _c
}

// SetError sets the "error" field.
func (_c *CompressionJobCreate) SetError(v string) *CompressionJobCreate {
	_c.mutation.SetError(v)
	return _c
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_c *CompressionJobCreate) SetNillableError(v *string) *CompressionJobCreate {
	if v != nil {
		_c.SetError(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *CompressionJobCreate) SetStartedAt(v time.Time) *CompressionJobCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *CompressionJobCreate) SetNillableStartedAt(v *time.Time) *CompressionJobCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *CompressionJobCreate) SetCompletedAt(v time.Time) *CompressionJobCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *CompressionJobCreate) SetNillableCompletedAt(v *time.Time) *CompressionJobCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CompressionJobCreate) SetID(v string) *CompressionJobCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *CompressionJobCreate) SetNillableID(v *string) *CompressionJobCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetAssetID sets the "asset" edge to the Asset entity by ID.
func (_c *CompressionJobCreate) SetAssetID(id string) *CompressionJobCreate {
	_c.mutation.SetAssetID(id)
	return _c
}

// SetAsset sets the "asset" edge to the Asset entity.
func (_c *CompressionJobCreate) SetAsset(v *Asset) *CompressionJobCreate {
	return _c.SetAssetID(v.ID)
}

// Mutation returns the CompressionJobMutation object of the builder.
func (_c *CompressionJobCreate) Mutation() *CompressionJobMutation {
	return _c.mutation
}

// Save creates the CompressionJob in the database.
func (_c *CompressionJobCreate) Save(ctx context.Context) (*CompressionJob, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CompressionJobCreate) SaveX(ctx context.Context) *CompressionJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CompressionJobCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CompressionJobCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CompressionJobCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := compressionjob.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Progress(); !ok {
		v := compressionjob.DefaultProgress
		_c.mutation.SetProgress(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := compressionjob.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CompressionJobCreate) check() error {
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "CompressionJob.status"`)}
	}
	if _, ok := _c.mutation.Progress(); !ok {
		return &ValidationError{Name: "progress", err: errors.New(`ent: missing required field "CompressionJob.progress"`)}
	}
	if len(_c.mutation.AssetIDs()) == 0 {
		return &ValidationError{Name: "asset", err: errors.New(`ent: missing required edge "CompressionJob.asset"`)}
	}
	return nil
}

func (_c *CompressionJobCreate) sqlSave(ctx context.Context) (*CompressionJob, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected CompressionJob.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CompressionJobCreate) createSpec() (*CompressionJob, *sqlgraph.CreateSpec) {
	var (
		_node = &CompressionJob{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(compressionjob.Table, sqlgraph.NewFieldSpec(compressionjob.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(compressionjob.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Progress(); ok {
		_spec.SetField(compressionjob.FieldProgress, field.TypeInt, value)
		_node.Progress = value
	}
	if value, ok := _c.mutation.Error(); ok {
		_spec.SetField(compressionjob.FieldError, field.TypeString, value)
		_node.Error = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(compressionjob.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(compressionjob.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = value
	}
	if nodes := _c.mutation.AssetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   compressionjob.AssetTable,
			Columns: []string{compressionjob.AssetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.asset_compression_jobs = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CompressionJobCreateBulk is the builder for creating many CompressionJob entities in bulk.
type CompressionJobCreateBulk struct {
	config
	err      error
	builders []*CompressionJobCreate
}

// Save creates the CompressionJob entities in the database.
func (_c *CompressionJobCreateBulk) Save(ctx context.Context) ([]*CompressionJob, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CompressionJob, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CompressionJobMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CompressionJobCreateBulk) SaveX(ctx context.Context) []*CompressionJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CompressionJobCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CompressionJobCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
