// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/adimail/asset-manager/ent/asset"
	"github.com/adimail/asset-manager/ent/compressionjob"
	"github.com/adimail/asset-manager/ent/predicate"
)

// CompressionJobUpdate is the builder for updating CompressionJob entities.
type CompressionJobUpdate struct {
	config
	hooks    []Hook
	mutation *CompressionJobMutation
}

// Where appends a list predicates to the CompressionJobUpdate builder.
func (_u *CompressionJobUpdate) Where(ps ...predicate.CompressionJob) *CompressionJobUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *CompressionJobUpdate) SetStatus(v string) *CompressionJobUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CompressionJobUpdate) SetNillableStatus(v *string) *CompressionJobUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProgress sets the "progress" field.
func (_u *CompressionJobUpdate) SetProgress(v int) *CompressionJobUpdate {
	_u.mutation.ResetProgress()
	_u.mutation.SetProgress(v)
	return _u
}

// SetNillableProgress sets the "progress" field if the given value is not nil.
func (_u *CompressionJobUpdate) SetNillableProgress(v *int) *CompressionJobUpdate {
	if v != nil {
		_u.SetProgress(*v)
	}
	return _u
}

// AddProgress adds value to the "progress" field.
func (_u *CompressionJobUpdate) AddProgress(v int) *CompressionJobUpdate {
	_u.mutation.AddProgress(v)
	return _u
}

// SetError sets the "error" field.
func (_u *CompressionJobUpdate) SetError(v string) *CompressionJobUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *CompressionJobUpdate) SetNillableError(v *string) *CompressionJobUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *CompressionJobUpdate) ClearError() *CompressionJobUpdate {
	_u.mutation.ClearError()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *CompressionJobUpdate) SetStartedAt(v time.Time) *CompressionJobUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *CompressionJobUpdate) SetNillableStartedAt(v *time.Time) *CompressionJobUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *CompressionJobUpdate) ClearStartedAt() *CompressionJobUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *CompressionJobUpdate) SetCompletedAt(v time.Time) *CompressionJobUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *CompressionJobUpdate) SetNillableCompletedAt(v *time.Time) *CompressionJobUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *CompressionJobUpdate) ClearCompletedAt() *CompressionJobUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetAssetID sets the "asset" edge to the Asset entity by ID.
func (_u *CompressionJobUpdate) SetAssetID(id string) *CompressionJobUpdate {
	_u.mutation.SetAssetID(id)
	return _u
}

// SetAsset sets the "asset" edge to the Asset entity.
func (_u *CompressionJobUpdate) SetAsset(v *Asset) *CompressionJobUpdate {
	return _u.SetAssetID(v.ID)
}

// Mutation returns the CompressionJobMutation object of the builder.
func (_u *CompressionJobUpdate) Mutation() *CompressionJobMutation {
	return _u.mutation
}

// ClearAsset clears the "asset" edge to the Asset entity.
func (_u *CompressionJobUpdate) ClearAsset() *CompressionJobUpdate {
	_u.mutation.ClearAsset()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CompressionJobUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CompressionJobUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CompressionJobUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CompressionJobUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CompressionJobUpdate) check() error {
	if _u.mutation.AssetCleared() && len(_u.mutation.AssetIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CompressionJob.asset"`)
	}
	return nil
}

func (_u *CompressionJobUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(compressionjob.Table, compressionjob.Columns, sqlgraph.NewFieldSpec(compressionjob.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(compressionjob.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Progress(); ok {
		_spec.SetField(compressionjob.FieldProgress, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProgress(); ok {
		_spec.AddField(compressionjob.FieldProgress, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(compressionjob.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(compressionjob.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(compressionjob.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(compressionjob.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(compressionjob.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(compressionjob.FieldCompletedAt, field.TypeTime)
	}
	if _u.mutation.AssetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   compressionjob.AssetTable,
			Columns: []string{compressionjob.AssetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   compressionjob.AssetTable,
			Columns: []string{compressionjob.AssetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{compressionjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CompressionJobUpdateOne is the builder for updating a single CompressionJob entity.
type CompressionJobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CompressionJobMutation
}

// SetStatus sets the "status" field.
func (_u *CompressionJobUpdateOne) SetStatus(v string) *CompressionJobUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CompressionJobUpdateOne) SetNillableStatus(v *string) *CompressionJobUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProgress sets the "progress" field.
func (_u *CompressionJobUpdateOne) SetProgress(v int) *CompressionJobUpdateOne {
	_u.mutation.ResetProgress()
	_u.mutation.SetProgress(v)
	return _u
}

// SetNillableProgress sets the "progress" field if the given value is not nil.
func (_u *CompressionJobUpdateOne) SetNillableProgress(v *int) *CompressionJobUpdateOne {
	if v != nil {
		_u.SetProgress(*v)
	}
	return _u
}

// AddProgress adds value to the "progress" field.
func (_u *CompressionJobUpdateOne) AddProgress(v int) *CompressionJobUpdateOne {
	_u.mutation.AddProgress(v)
	return _u
}

// SetError sets the "error" field.
func (_u *CompressionJobUpdateOne) SetError(v string) *CompressionJobUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *CompressionJobUpdateOne) SetNillableError(v *string) *CompressionJobUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *CompressionJobUpdateOne) ClearError() *CompressionJobUpdateOne {
	_u.mutation.ClearError()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *CompressionJobUpdateOne) SetStartedAt(v time.Time) *CompressionJobUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *CompressionJobUpdateOne) SetNillableStartedAt(v *time.Time) *CompressionJobUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *CompressionJobUpdateOne) ClearStartedAt() *CompressionJobUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *CompressionJobUpdateOne) SetCompletedAt(v time.Time) *CompressionJobUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *CompressionJobUpdateOne) SetNillableCompletedAt(v *time.Time) *CompressionJobUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *CompressionJobUpdateOne) ClearCompletedAt() *CompressionJobUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetAssetID sets the "asset" edge to the Asset entity by ID.
func (_u *CompressionJobUpdateOne) SetAssetID(id string) *CompressionJobUpdateOne {
	_u.mutation.SetAssetID(id)
	return _u
}

// SetAsset sets the "asset" edge to the Asset entity.
func (_u *CompressionJobUpdateOne) SetAsset(v *Asset) *CompressionJobUpdateOne {
	return _u.SetAssetID(v.ID)
}

// Mutation returns the CompressionJobMutation object of the builder.
func (_u *CompressionJobUpdateOne) Mutation() *CompressionJobMutation {
	return _u.mutation
}

// ClearAsset clears the "asset" edge to the Asset entity.
func (_u *CompressionJobUpdateOne) ClearAsset() *CompressionJobUpdateOne {
	_u.mutation.ClearAsset()
	return _u
}

// Where appends a list predicates to the CompressionJobUpdate builder.
func (_u *CompressionJobUpdateOne) Where(ps ...predicate.CompressionJob) *CompressionJobUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CompressionJobUpdateOne) Select(field string, fields ...string) *CompressionJobUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CompressionJob entity.
func (_u *CompressionJobUpdateOne) Save(ctx context.Context) (*CompressionJob, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CompressionJobUpdateOne) SaveX(ctx context.Context) *CompressionJob {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CompressionJobUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CompressionJobUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CompressionJobUpdateOne) check() error {
	if _u.mutation.AssetCleared() && len(_u.mutation.AssetIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CompressionJob.asset"`)
	}
	return nil
}

func (_u *CompressionJobUpdateOne) sqlSave(ctx context.Context) (_node *CompressionJob, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(compressionjob.Table, compressionjob.Columns, sqlgraph.NewFieldSpec(compressionjob.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CompressionJob.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, compressionjob.FieldID)
		for _, f := range fields {
			if !compressionjob.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != compressionjob.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(compressionjob.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Progress(); ok {
		_spec.SetField(compressionjob.FieldProgress, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProgress(); ok {
		_spec.AddField(compressionjob.FieldProgress, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(compressionjob.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(compressionjob.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(compressionjob.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(compressionjob.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(compressionjob.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(compressionjob.FieldCompletedAt, field.TypeTime)
	}
	if _u.mutation.AssetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   compressionjob.AssetTable,
			Columns: []string{compressionjob.AssetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   compressionjob.AssetTable,
			Columns: []string{compressionjob.AssetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CompressionJob{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{compressionjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
