// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/adimail/asset-manager/ent/asset"
	"github.com/adimail/asset-manager/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	assetFields := schema.Asset{}.Fields()
	_ = assetFields
	// assetDescOriginalFilename is the schema descriptor for original_filename field.
	assetDescOriginalFilename := assetFields[1].Descriptor()
	// asset.OriginalFilenameValidator is a validator for the "original_filename" field. It is called by the builders before save.
	asset.OriginalFilenameValidator = assetDescOriginalFilename.Validators[0].(func(string) error)
	// assetDescFileSizeBytes is the schema descriptor for file_size_bytes field.
	assetDescFileSizeBytes := assetFields[4].Descriptor()
	// asset.FileSizeBytesValidator is a validator for the "file_size_bytes" field. It is called by the builders before save.
	asset.FileSizeBytesValidator = assetDescFileSizeBytes.Validators[0].(func(int64) error)
	// assetDescCreatedAt is the schema descriptor for created_at field.
	assetDescCreatedAt := assetFields[6].Descriptor()
	// asset.DefaultCreatedAt holds the default value on creation for the created_at field.
	asset.DefaultCreatedAt = assetDescCreatedAt.Default.(func() time.Time)
}
